name: xapp
description: A platform for everyone to share their ideas with everyone

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  fluttertoast: ^3.1.3
  shared_preferences: ^0.5.6+2
  flutter_spinkit: ^4.1.2
  cloud_firestore: ^0.13.3
  firebase_core: ^0.4.4
  firebase_auth: ^0.15.4
  firebase_storage: ^3.1.1
  simple_animations: ^1.3.7
  auto_animated: ^2.0.1
  provider: ^4.0.4
  font_awesome_flutter: ^8.7.0
  line_icons: ^0.2.0
  fade: ^1.0.0
  dotted_border: ^1.0.5
  circular_check_box: ^1.0.1
  bubble: ^1.1.9+1
  flutter_launcher_icons: ^0.7.4
  rect_getter: ^0.1.0
  flutter_page_transition: ^0.1.6
  photo_view: ^0.9.2
  flappy_search_bar: ^1.7.2
  cached_network_image: ^2.1.0+1
  google_fonts: ^1.0.0
  nice_intro: ^0.1.2
  image_picker: ^0.6.6+1
  video_trimmer: ^0.2.3
  progressive_image: ^1.0.1
  video_player: ^0.10.11+1
  flutter_video_compress: ^0.3.7+8
  flutter_typeahead: ^1.8.1
  highlight_text: ^0.7.2

flutter_icons:
  android: true
  ios: true
  image_path_android: "images/launcher_logo.jpg"
  image_path_ios: "images/launcher_logo.jpg"
  adaptive_icon_background: "images/just_bg.png"
  adaptive_icon_foreground: "images/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

  fonts:
    - family: Product Sans
      fonts:
        - asset: fonts/product_sans_bold.ttf
        - asset: fonts/product_sans_regular.ttf
    - family: Open Sans
      fonts:
        - asset: fonts/open_sans.ttf
    - family: McLaren
      fonts:
        - asset: fonts/McLaren_regular.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
